title: Faktiskt
email: faktiskt@faktiskt.com
description: "Här hittar du fakta för att bemöta felaktiga föreställningar om jämställdhet, miljö, migration och ekonomi."
baseurl: ""
url: "http://faktiskt.com/"
twitter_username: faktiskt
github_username:  faktiskt

permalink: pretty
markdown: rdiscount

prose:
  siteurl: 'http://faktiskt.com/'
  media: 'images'
  relativeLinks: 'http://faktiskt.com/links.jsonp'
  ignore:
    - .gitignore
    - _config.yml
    - /_layouts
    - /_includes
    - /links.jsonp
    - /css/
  metadata:
    ekonomi:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: "Post"
              value: "post"
            - name: "Post Index"
              value: "postindex"
            - name: "Index"
              value: "index"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
          value: ""
      - name: "sort"
        field:
          element: "number"
          label: "Sortering"
          value: ""
    jamstalldhet:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: "Post"
              value: "post"
            - name: "Post Index"
              value: "postindex"
            - name: "Index"
              value: "index"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
          value: ""
      - name: "sort"
        field:
          element: "number"
          label: "Sortering"
          value: ""
    migration:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: "Post"
              value: "post"
            - name: "Post Index"
              value: "postindex"
            - name: "Index"
              value: "index"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
          value: ""
      - name: "sort"
        field:
          element: "number"
          label: "Sortering"
          value: ""
    miljo:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: "Post"
              value: "post"
            - name: "Post Index"
              value: "postindex"
            - name: "Index"
              value: "index"
      - name: "title"
        field:
          element: "text"
          label: "Titel"
          value: ""
      - name: "sort"
        field:
          element: "number"
          label: "Sortering"
          value: ""
