# Site settings
title: Faktiskt
email: faktiskt@faktiskt.com
description: "Här hittar du fakta för att bemöta felaktiga föreställningar om jämställdhet, miljö, migration och ekonomi."
baseurl: ""
url: "http://jamkatt.github.io/faktiskt"
twitter_username: faktiskt
github_username:  faktiskt

# Build settings
markdown: kramdown
permalink: pretty
